command: pwsh.exe
cwd: null
env:
  recording: true
cols: auto
rows: auto
repeat: 0
quality: 100
frameDelay: auto
maxIdleTime: 400
frameBox:
  type: window
  title: PowerShell 7
  style:
    border: 0px solid rgb(0, 0, 0)
    boxShadow: 8px 8px 16px grey
watermark:
  imagePath: null
cursorStyle: underline
fontFamily: "Consolas, Lucida Console, Monaco, Ubuntu Mono, Monospace"
fontSize: 14
lineHeight: 1
letterSpacing: 0
theme:
  background: "#282a48"
  foreground: "#eeedf0"
  cursor: "#c7c7c7"
  black: "#282a48"
  red: "#bf0000"
  green: "#008000"
  yellow: "#f2c800"
  blue: "#4472c4"
  magenta: "#8a3cc4"
  cyan: "#ff7e00"
  white: "#c0c0c0"
  brightBlack: "#808080"
  brightRed: "#fe2020"
  brightGreen: "#92d050"
  brightYellow: "#f2f200"
  brightBlue: "#3d94f3"
  brightMagenta: "#fe8cff"
  brightCyan: "#42e0d1"
  brightWhite: "#a8a8a8"